theme: jekyll-theme-midnight
title: Welcome to [Ally Page](https://github.com/williamsasp)
description: Young software and project developer aiming to learn all she can to earn a career in Computing Field
